<!DOCTYPE html>

<html lang="zh-cmn-Hans" xmlns:ng="http://angularjs.org" ng-app="app">
<head>
  <meta charset="utf-8" />
  <title>福利商城</title>

  <meta name="description" content="福利商城" />
  <meta name="keywords" content="福利商城" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
  <meta content="yes" name="apple-mobile-web-app-capable">
  <meta content="yes" name="apple-touch-fullscreen">
  <meta content="telephone=no,email=no" name="format-detection">

  <link rel="apple-touch-icon-precomposed" href="image/apple-touch-icon.png">
  <link rel="apple-touch-icon" href="image/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="57x57" href="image/icon/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="image/icon/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="image/icon/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="image/icon/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="image/icon/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="image/icon/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="image/icon/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="image/icon/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="image/icon/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="image/icon/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="image/icon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="image/icon/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="image/icon/favicon-16x16.png">
  <link rel="manifest" href="/static/image/icon/manifest.json">

  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

  <!-- build:css css/app.base.css -->
  <link rel="stylesheet" href="/static/css/reset.css" type="text/css" />
  <!-- endbuild -->

  <!-- build:css css/app.main.css -->
  <link rel="stylesheet" href="/static/css/app.css?v=12" type="text/css" />
  <!-- endbuild -->
</head>

<body id="ng-app"
      ng-controller="AppController"
      ng-class="{'is-ie': app.useragent.isIE, 'is-weixin': app.useragent.isWeixin, 'is-mobile': app.useragent.isMobile, 'is-browser': app.useragent.isBrowser}">

  <div class="app" id="app" ui-view>

    <div class="app-container with-navbar with-tabbar" ng-controller="HomeController">
        <div class="navbar fixed-top">
            <div class="head_handel_wrap flex-h">
                <div class="ctiy_opt_box flex-h" ng-class="{true:'ctiy_opt_boxone', false: ''}[showRegionList]" ng-click="changeRegionShow();"> <!-- ctiy_opt_boxone -->
                    <span class="ctiy_opt_name">全国</span>
                    <img src="/static/image/home/city_lists.png">
                    <ul class="ctiy_list_wrap">
                        <li class="ctiy_curt" ng-click="changeLocation(0);">全国</li>
                        <li ng-class="{2:'ctiy_curt', false: ''}[user_city_id]" ng-click="changeLocation(2);">北京</li>
                        <li ng-class="{10:'ctiy_curt', false: ''}[user_city_id]" ng-click="changeLocation(10);">上海</li>
                    </ul>
                </div>

                <div class="search flex1" ng-click="touchSearch()">
                    <img class="search-icon" src="/static/image/ind-search.png"/>
                    <span class="search-text">请输入您要搜索的商品</span>
                </div>
            </div>
        </div>

        <div class="app-content">

            <!-- Banner -->
            <div class="home-banner swiper-container">
                <div class="swiper-wrapper">
                    <div class="banner-slide swiper-slide" >
                        <img src="/static/image/default-photo.png" class="slide-image"/>
                    </div>
                </div>
                <div class="swiper-pagination"></div>
            </div>

            <!-- Menu -->
            <div class="home-menu">
                <div class="menu-item" >
                    <a href="http://shop.xindongguoji.com/h5/#/category">
                        <img class="item-icon" src="/static/image/home/stadium.png"/>
                        <div class="item-text">场馆预订</div>
                    </a>
                </div>
                <div class="menu-item" >
                    <a href="http://shop.xindongguoji.com/h5/#/category">
                        <img class="item-icon" src="/static/image/home/sport_equipment.png"/>
                        <div class="item-text">运动装备</div>
                    </a>
                </div>
                <div class="menu-item" >
                        <img class="item-icon" src="/static/image/home/outdoors.png"/>
                        <div class="item-text">户外休闲</div>
                </div>
                <div class="menu-item" >
                    <a href="http://shop.xindongguoji.com/h5/#/search-result/?sortKey=0&sortValue=0&category=1959&navTitle=%E5%A2%9E%E5%80%BC%E6%9C%8D%E5%8A%A1&navStyle=default">
                        <img class="item-icon" src="/static/image/home/value_service.png"/>
                        <div class="item-text">增值服务</div>
                    </a>
                </div>

                <div class="menu-item" >
                    <a href="http://shop.xindongguoji.com/h5/#/search-result/?sortKey=0&sortValue=0&category=1771&navTitle=%E8%BF%90%E5%8A%A8%E7%A5%A8%E5%8A%A1&navStyle=default" >
                        <img class="item-icon" src="/static/image/home/games.png"/>
                        <div class="item-text">运动票务</div>
                    </a>
                </div>
                <div class="menu-item" >
                    <a href="http://shop.xindongguoji.com/h5/#/search-result/?sortKey=0&sortValue=0&category=1967&navTitle=%E5%A5%B3%E6%80%A7%E4%B8%93%E5%8C%BA&navStyle=default">
                        <img class="item-icon" src="/static/image/home/famale.png"/>
                        <div class="item-text">女性专区</div>
                    </a>
                </div>
                <div class="menu-item" >
                    <a href="http://shop.xindongguoji.com/h5/#/search-result/?sortKey=0&sortValue=0&category=1968&navTitle=%E5%9B%A2%E9%98%9F%E6%B4%BB%E5%8A%A8&navStyle=default">
                    <img class="item-icon" src="/static/image/home/team_building.png"/>
                    <div class="item-text">团队服务</div>
                    </a>
                </div>
                <div class="menu-item" >
                    <a href="http://shop.xindongguoji.com/h5/#/search-result/?sortKey=0&sortValue=0&category=1960&navTitle=%E8%9B%8B%E7%B3%95&navStyle=default">
                    <img class="item-icon" src="/static/image/home/other.png"/>
                    <div class="item-text">其他</div>
                    </a>
                </div>
            </div>

            <!-- Notice -->
            <div class="home-notice" ng-if="notices && notices.length">
                <img class="notice-icon" src="/static/image/home-notice.png"/>
                <div class="notice-vline"></div>
                <div class="notice-slide swiper-container">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide" ng-repeat="notice in notices track by $index" ng-click="touchNotice(notice)">
                            商店通知。。。。。。
                        </div>
                    </div>
                </div>
            </div>

            <!-- Editor Choices -->
            <div class="home-product" ng-if="editorChoice && editorChoice.length">
                <div class="product-header" ng-click="touchEditorChoice()">
                    <!-- <img class="header-arrow" src="/static/image/nav-right.png"/> -->
                    <div class="header-title">精品推荐</div>
                </div>
                <div class="product-item" ng-repeat="product in editorChoice track by $index" ng-click="touchProduct(product)">
                    <div class="item-photo">
                        <img src="/static/image/default-photo.png" lazy-img="{{product.default_photo.large}}"/>
                    </div>
                    <div class="item-name">测试商品名称</div>
                    <div class="item-price">323.44￥</div>
                </div>
            </div>

            <!-- New arrival -->
            <div class="home-product" ng-if="newArrival && newArrival.length">
                <div class="product-header" ng-click="touchNewArrival()">
                    <!-- <img class="header-arrow" src="/static/image/nav-right.png"/> -->
                    <div class="header-title">新品上架</div>
                </div>
                <div class="product-item" ng-repeat="product in newArrival track by $index" ng-click="touchProduct(product)">
                    <div class="item-photo">
                        <img src="/static/image/default-photo.png" lazy-img="{{product.default_photo.large}}"/>
                    </div>
                    <div class="item-name">测试商品名称</div>
                    <div class="item-price">444.66￥</div>
                </div>
            </div>

            <!-- Top sale -->
            <div class="home-product" ng-if="topSale && topSale.length">
                <div class="product-header" ng-click="touchTopSale()">
                    <!-- <img class="header-arrow" src="/static/image/nav-right.png"/> -->
                    <div class="header-title">销量排行</div>
                </div>
                <div class="product-item">
                    <div class="item-photo">
                        <img src="/static/image/default-photo.png" lazy-img="{{product.default_photo.large}}"/>
                    </div>
                    <div class="item-name">测试商品-adidas运动鞋</div>
                    <div class="item-price">5555￥</div>
                </div>
                <div class="product-item">
                    <div class="item-photo">
                        <img src="/static/image/default-photo.png" lazy-img="{{product.default_photo.large}}"/>
                    </div>
                    <div class="item-name">测试商品-adidas运动鞋</div>
                    <div class="item-price">5555￥</div>
                </div>
                <div class="product-item">
                    <div class="item-photo">
                        <img src="/static/image/default-photo.png" lazy-img="{{product.default_photo.large}}"/>
                    </div>
                    <div class="item-name">测试商品-adidas运动鞋</div>
                    <div class="item-price">5555￥</div>
                </div>
                <div class="product-item">
                    <div class="item-photo">
                        <img src="/static/image/default-photo.png" lazy-img="{{product.default_photo.large}}"/>
                    </div>
                    <div class="item-name">测试商品-adidas运动鞋</div>
                    <div class="item-price">5555￥</div>
                </div>
                <div class="product-item">
                    <div class="item-photo">
                        <img src="/static/image/default-photo.png" lazy-img="{{product.default_photo.large}}"/>
                    </div>
                    <div class="item-name">测试商品-adidas运动鞋</div>
                    <div class="item-price">5555￥</div>
                </div>
            </div>

        </div>

        <div class="tabbar fixed-bottom">
          <div class="tab active" ng-click="goHome()">
            <img class="tab-icon" src="/static/image/tab-home-active.png"/>
          </div>
          <div class="tab" ng-click="goCategory()">
            <img class="tab-icon" src="/static/image/tab-category-normal.png"/>
          </div>
          <div class="tab" ng-click="goCart()">
            <img class="tab-icon" src="/static/image/tab-cart-normal.png"/>
            <div class="tab-badge" ng-if="cartModel.total > 0">
                10
            </div>
          </div>
          <div class="tab" ng-click="goProfile()">
            <img class="tab-icon" src="/static/image/tab-profile-normal.png"/>
          </div>
        </div>

    </div>

  </div>

    <!-- <div class="splash" id="splash">
        <div class="inner">
          <img src="/static/image/loading.png"/>
        </div>
    </div> -->
    <script type="text/javascript">
        // $(window).load(function(){
        //     var el = $('#splash');
        //     el.fadeOut(500, function(){
        //         el.remove();
        //     });
        // })
    </script>
</body>
</html>
