<!DOCTYPE html>

<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8" />
    <title>福利商城-用户登录</title>

    <meta name="description" content="福利商城" />
    <meta name="keywords" content="福利商城" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="yes" name="apple-touch-fullscreen">
    <meta content="telephone=no,email=no" name="format-detection">

    <link rel="stylesheet" href="/static/css/common.css?v=1" type="text/css" />
    <link rel="stylesheet" href="/static/css/login.css?v=1" type="text/css" />
</head>

<body id="ng-app" class="ng-scope is-browser">

<div class="app-container with-navbar" ng-controller="SigninController">

    <div class="navbar fixed-top">
        <div class="navbar-left hide-weixin" ng-click="goHome()">
            <img class="button-icon" src="/static/image/nav-left.png"/>
            <div class="button-text">取消</div>
        </div>
        <div class="navbar-title">
            用户登录
        </div>
    </div>

    <div class="app-content">
        <div class="logo">
            <img class="field-icon" src="/static/image/company_logo_new.png?v=2" />
            <p class="logIn_tit">企业员工登录</p>
        </div>
        <div class="signin-form">
            <div class="signin-field">
                <img class="field-icon" src="/static/image/ind-username.png"/>
                <input class="field-input" placeholder="手机号" ng-model="telphone"/>
            </div>
            <div class="signin-hline"></div>
            <div class="signin-field">
                <img class="field-icon" src="/static/image/ind-password.png"/>
                <input type="password" class="field-input" placeholder="请输入密码" ng-model="password"/>
            </div>
        </div>
        <div class="signin-submit" ng-click="touchTelphoneSignin()">
            登录
        </div>
        <div class="signin-other">
            <div class="other-item abs-left" ng-click="goCodeSignin()">验证码登录</div>
            <div class="other-item abs-right" ng-click="touchForget()">忘记密码?</div>
        </div>

    </div>

</div>




</body>

</html>
